server:
  port: 9025
  
spring:
  datasource:
    url:  jdbc:oracle:thin:@davidpracticerevaturedbinstance.cxfabdl3wcfh.us-east-2.rds.amazonaws.com:1521:orcl
    username: Swarbrick857
    password: p4ssw0rd
    driver-class-name:  oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
