server:
  port: 9025
  
spring:
  datasource:
    url:  
    username: 
    password: 
    driver-class-name:  oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
